name: CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Code lint
        run: npm run lint

  build:
    needs: code-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  test:
    needs:
      - code-check
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Test project
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    needs:
      - code-check
      - build
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Deploy to server
        id: deployment
        run: |
          # Sample deploy to the server
          # ssh user@<SERVER_IP> "cd /path/to/project && git pull && npm install && npm run build"
  run-python-check:
    needs: 
      - code-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Run check script
        env:
          LINES_ADDED: ${{ steps.diff.outputs.additions }}
          LINES_DELETED: ${{ steps.diff.outputs.deletions }}
          CHANGED_FILES: ${{ steps.diff.outputs.changes }}
        run: |
          python cs_check.py $LINES_ADDED $LINES_DELETED $CHANGED_FILES
