name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coding-standards-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the commit SHA
        id: commit-sha
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Get list of changed files
        id: changed-files
        uses: actions/github-script@v6
        with:
          script: |
            const baseSha = context.payload.before;
            const headSha = context.payload.after;
            const { data: comparison } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: baseSha,
              head: headSha,
            });
            const changedFiles = comparison.files.map(file => file.filename);
            console.log(`Changed files: ${JSON.stringify(changedFiles)}`);
            core.setOutput('changedFiles', JSON.stringify(changedFiles));
      - name: Send changed files to endpoint
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const FormData = require('form-data');

            const changedFiles = JSON.parse(
              '${{ steps.changed-files.outputs.changedFiles }}',
            );

            const formData = new FormData();
            const file_paths = [];


            for (const file of changedFiles) {
                formData.append('files', fs.createReadStream(filePath));
                file_paths.push(file);
            }

            formData.append('file_paths', file_paths);
            formData.append('threshold', '0.1');
            formData.append('repo_name', '${{ github.repository }}');
            formData.append('owner_name', '${{ github.repository_owner }}');
            formData.append('pr_number', '${{ github.event.number }}');

            console.log('Form data:', formData);

            const response = await fetch(
              'https://dev-appmod.techo.camp/pr_push_check/css_validation_api',
              {
                method: 'POST',
                headers: { ...form.getHeaders() },
                body: formData,
              },
            );

            console.log("Response:", response);

            if (!response.ok) {
              throw new Error('Failed to send changed files to endpoint');
            }

            const data = await response.json();
            console.log('Data:', data);

# --form 'files=@"/C:/Users/Mohak Khatri/Desktop/comment_script/repo/new.py"'
